# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-20 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='city',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signature',
            name='street',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signature',
            name='zip',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
