# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-20 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0002_auto_20170120_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signature',
            name='zip',
        ),
        migrations.AddField(
            model_name='signature',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signature',
            name='opt_in',
            field=models.BooleanField(default=True, verbose_name='Keep me updated on this issue'),
        ),
        migrations.AddField(
            model_name='signature',
            name='show_name',
            field=models.BooleanField(default='', verbose_name="Don't display my name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signature',
            name='zip_code',
            field=models.CharField(default='', max_length=5, verbose_name='zip code'),
            preserve_default=False,
        ),
    ]
