# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-24 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0003_auto_20170120_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='description',
            field=models.TextField(default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petition',
            name='goal',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='petition',
            name='letter',
            field=models.TextField(default='', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petition',
            name='region',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
