# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-24 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0004_auto_20170124_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='address_to',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petition',
            name='created_by',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
