# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-24 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0005_auto_20170124_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='hero_image',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
