# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-24 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0008_auto_20170124_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='region',
        ),
        migrations.AddField(
            model_name='signature',
            name='city',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
