# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-24 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0010_auto_20170124_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='comment',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
