# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-24 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0011_signature_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='comment',
            field=models.TextField(max_length=500),
        ),
    ]
