# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-27 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0012_auto_20170124_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signature',
            old_name='first',
            new_name='first_name',
        ),
    ]
