# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-27 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0013_auto_20170127_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signature',
            old_name='last',
            new_name='last_name',
        ),
    ]
