# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-29 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0015_auto_20170127_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='teaser_text',
            field=models.CharField(default='', help_text='Appears in search results, and social media shares.', max_length=255),
            preserve_default=False,
        ),
    ]
