# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-29 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0016_petition_teaser_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='comment',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
