# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-29 23:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0017_auto_20170129_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 1, 29, 23, 36, 35, 270465, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signature',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 1, 29, 23, 36, 43, 857139, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
