# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-04 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0019_petition_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='petition',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='petition.Petition'),
        ),
    ]
