# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-13 03:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0021_petition_thank_you_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
